export const CARRIER_CONTENT = {
  list: {
    kicker: 'Carriers',
    title: 'Carrier Table',
    description:
      'Manage carrier records with reusable TanStack Table columns, pagination, and action controls.',
    addButton: 'Add Carrier',
    loadErrorFallback: 'Unable to load carriers. Please try again.',
    retry: 'Retry',
  },
  pages: {
    new: {
      formTitle: 'New Carrier',
    },
  },
  table: {
    emptyValue: '-',
    columns: {
      name: 'Name',
      groupTitle: 'Group Title',
      phone: 'Phone',
      edit: 'Edit',
      delete: 'Delete',
    },
    editAria: (name: string) => `Edit ${name}`,
    deleteAria: (name: string) => `Delete ${name}`,
  },
  form: {
    defaultTitle: 'New Carrier',
    labels: {
      name: 'Name',
      groupTitle: 'Group Title',
      address1: 'Address 1',
      address2: 'Address 2',
      city: 'City',
      state: 'State',
      zip: 'ZIP Code',
      contactFirstName: 'Contact First Name',
      contactLastName: 'Contact Last Name',
      phone: 'Phone',
      fax: 'Fax',
      email: 'Email',
    },
    placeholders: {
      name: 'Enter carrier name',
      groupTitle: 'Enter group title',
      address1: 'Enter address line 1',
      address2: 'Enter address line 2',
      city: 'Enter city',
      zip: 'Enter ZIP code',
      contactFirstName: 'Enter contact first name',
      contactLastName: 'Enter contact last name',
      phone: '(___) ___-____',
      fax: '(___) ___-____',
      email: 'Enter email address',
    },
    stateLoading: 'Loading...',
    statePlaceholder: 'Select state...',
    stateLoadError: 'Failed to load states. Please refresh.',
    validationSummary: 'Please fix the highlighted fields before saving.',
    actions: {
      back: 'Back',
      save: 'Save',
    },
  },
  validation: {
    nameRequired: 'Name is required',
    nameMax: 'Name must be 100 characters or fewer',
    groupTitleRequired: 'Group Title is required',
    groupTitleMax: 'Group Title must be 100 characters or fewer',
    addressMax: 'Address must be 200 characters or fewer',
    cityMax: 'City must be 100 characters or fewer',
    cityLetters: 'City must contain only letters',
    zipInvalid: 'Enter a valid ZIP code (e.g. 12345 or 12345-6789)',
    firstNameMax: 'First name must be 50 characters or fewer',
    firstNameLetters: 'First name must contain only letters',
    lastNameMax: 'Last name must be 50 characters or fewer',
    lastNameLetters: 'Last name must contain only letters',
    phoneInvalid: 'Enter a valid phone number — (___) ___-____',
    faxInvalid: 'Enter a valid fax number — (___) ___-____',
    emailInvalid: 'Enter a valid email address',
    emailMax: 'Email must be 254 characters or fewer',
  },
  toasts: {
    createSuccess: 'Carrier created successfully!',
    createError: 'Failed to create carrier. Please try again.',
  },
} as const
