export const CARRIER_CONTENT = {
  list: {
    kicker: 'Carriers',
    title: 'Carrier Table',
    description:
      'Manage carrier records with reusable TanStack Table columns, pagination, and action controls.',
    addButton: 'Add Carrier',
    loadErrorFallback: 'Unable to load carriers. Please try again.',
    retry: 'Retry',
  },
  pages: {
    index: {
      kicker: 'Administration',
      title: 'Update Carriers',
      description:
        'Select an action below to set up a new carrier or manage existing carriers.',
      chooseHeading: 'Please Choose',
      cards: {
        list: {
          title: 'List Carrier',
          description: 'View available carriers table',
        },
        new: {
          title: 'New Carrier',
          description: 'Guided Carrier Setup',
        },
      },
    },
    new: {
      formTitle: 'New Carrier',
    },
  },
  table: {
    emptyValue: '-',
    columns: {
      name: 'Name',
      groupTitle: 'Group Title',
      phone: 'Phone',
      edit: 'Edit',
      delete: 'Delete',
    },
    editAria: (name: string) => `Edit ${name}`,
    deleteAria: (name: string) => `Delete ${name}`,
  },
  form: {
    kicker: 'Site Manager',
    defaultTitle: 'New Carrier',
    titles: {
      create: 'Create Carrier',
      edit: 'Edit Carrier',
    },
    saveLabels: {
      create: 'Save',
      edit: 'Save Changes',
    },
    navigation: {
      back: 'Back',
      next: 'Next',
    },
    steps: [
      { id: 'general', label: 'General', index: 0 },
      { id: 'contact', label: 'Contact', index: 1 },
      { id: 'review', label: 'Review', index: 2 },
    ],
    labels: {
      name: 'Name',
      groupTitle: 'Group Title',
      address1: 'Address 1',
      address2: 'Address 2',
      city: 'City',
      state: 'State',
      zip: 'ZIP Code',
      contactFirstName: 'Contact First Name',
      contactLastName: 'Contact Last Name',
      phone: 'Phone',
      fax: 'Fax',
      email: 'Email',
      allowFlexibleDates: 'Allow Flexible Dates',
    },
    placeholders: {
      name: 'Enter carrier name',
      groupTitle: 'Enter group title',
      address1: 'Enter address line 1',
      address2: 'Enter address line 2',
      city: 'Enter city',
      zip: 'Enter ZIP code',
      contactFirstName: 'Enter contact first name',
      contactLastName: 'Enter contact last name',
      phone: '(___) ___-____',
      fax: '(___) ___-____',
      email: 'Enter email address',
    },
    stateLoading: 'Loading...',
    statePlaceholder: 'Select state...',
    stateLoadError: 'Failed to load states. Please refresh.',
    validationSummary: 'Please fix the highlighted fields before saving.',
    actions: {
      back: 'Back',
      save: 'Save',
    },
  },
  generalStep: {
    nameLabel: 'Name',
    namePlaceholder: 'Enter carrier name',
    groupTitleLabel: 'Group Title',
    groupTitlePlaceholder: 'Enter group title',
    allowFlexibleDatesLabel: 'Allow Flexible Dates',
    additionalDetailsHeading: 'Additional Details',
    address1Label: 'Address 1',
    address1Placeholder: 'Enter address line 1',
    address2Label: 'Address 2',
    address2Placeholder: 'Enter address line 2',
    cityLabel: 'City',
    cityPlaceholder: 'Enter city',
    stateLabel: 'State',
    stateLoadingPlaceholder: 'Loading...',
    stateSelectPlaceholder: 'Select a state',
    stateLoadError: 'Failed to load states. Please refresh.',
    zipCodeLabel: 'ZIP Code',
    zipCodePlaceholder: 'Enter ZIP code',
  },
  contactStep: {
    heading: 'Primary Contact Information',
    description: 'Enter the main contact details for this carrier.',
    firstNameLabel: 'Contact First Name',
    firstNamePlaceholder: 'ex. John',
    lastNameLabel: 'Contact Last Name',
    lastNamePlaceholder: 'ex. Doe',
    phoneLabel: 'Phone Number',
    phonePlaceholder: '(___) ___-____',
    faxLabel: 'Fax Number',
    faxPlaceholder: '(___) ___-____',
    emailLabel: 'Email Address',
    emailPlaceholder: 'ex. john.doe@example.com',
  },
  reviewStep: {
    heading: 'Review & Save',
    description: 'Confirm all details before saving the carrier.',
    emptyValue: '—',
    yes: 'Yes',
    no: 'No',
    sections: {
      general: 'General Information',
      primaryAddress: 'Primary Address',
      contact: 'Contact Information',
    },
    fields: {
      name: 'Name',
      groupTitle: 'Group Title',
      allowFlexibleDates: 'Allow Flexible Dates',
      address1: 'Address 1',
      address2: 'Address 2',
      city: 'City',
      state: 'State',
      zip: 'ZIP Code',
      contactFirstName: 'First Name',
      contactLastName: 'Last Name',
      phone: 'Phone Number',
      fax: 'Fax Number',
      email: 'Email Address',
    },
  },
  validation: {
    nameRequired: 'Name is required',
    nameMax: 'Name must be 100 characters or fewer',
    groupTitleRequired: 'Group Title is required',
    groupTitleMax: 'Group Title must be 100 characters or fewer',
    addressMax: 'Address must be 200 characters or fewer',
    cityMax: 'City must be 100 characters or fewer',
    cityLetters: 'City must contain only letters',
    zipInvalid: 'Enter a valid ZIP code (e.g. 12345 or 12345-6789)',
    firstNameMax: 'First name must be 50 characters or fewer',
    firstNameLetters: 'First name must contain only letters',
    lastNameMax: 'Last name must be 50 characters or fewer',
    lastNameLetters: 'Last name must contain only letters',
    phoneInvalid: 'Enter a valid phone number — (___) ___-____',
    faxInvalid: 'Enter a valid fax number — (___) ___-____',
    emailInvalid: 'Enter a valid email address',
    emailMax: 'Email must be 254 characters or fewer',
  },
  toasts: {
    createSuccess: 'Carrier created successfully!',
    createError: 'Failed to create carrier. Please try again.',
  },
} as const
