export const COVERAGE_CODE_CONTENT = {
  list: {
    kicker: 'Site Manager',
    title: 'Coverage Codes',
    description:
      'Manage coverage code records and pricing rules with reusable TanStack Table columns, server-side pagination, and action controls.',
    addButton: 'New Coverage Code',
    loadErrorFallback: 'Unable to load coverage codes. Please try again.',
    retry: 'Retry',
  },
  pages: {
    index: {
      kicker: 'Administration',
      title: 'Update Coverage Codes',
      description:
        'Select an action below to set up a new coverage code or manage existing coverage codes.',
      chooseHeading: 'Please Choose',
      cards: {
        list: {
          title: 'List Coverage Code',
          description: 'View available coverage codes table',
        },
        new: {
          title: 'New Coverage Code',
          description: 'Guided Coverage Code Setup',
        },
        update: {
          title: 'Update Current Coverage Code',
          description: 'Update Available Coverage Codes',
        },
      },
    },
    new: {
      formTitle: 'New Coverage Code',
    },
    edit: {
      kicker: 'Administration',
      title: 'Coverage Code Edit',
      description:
        'Select a coverage code to load its details, then update using the same guided steps as new setup.',
      selectLabel: 'Select Coverage Code',
      selectCardDescription:
        'Search the list below and choose a coverage code to load its profile for editing.',
      selectPlaceholder: 'Choose a coverage code',
      selectLoadingPlaceholder: 'Loading coverage codes...',
      selectSearchPlaceholder: 'Search coverage codes...',
      selectNoResults: 'No coverage codes match your search.',
      selectPrompt: 'Choose a coverage code from the dropdown to continue.',
      emptyStateTitle: 'Ready when you are',
      editingLabel: 'Editing:',
      loadingDetails: 'Loading coverage code details...',
      searchPlaceholder: 'Search by coverage code...',
      searchButton: 'Search',
      clearButton: 'Clear',
      viewTitle: 'Coverage Code Details',
      viewDescription: 'View complete details for the selected coverage code record.',
      deleteButton: 'Delete',
      backButton: 'Back',
      editButton: 'Edit',
      confirmDeleteTitle: 'Delete Coverage Code',
      confirmDeletePrompt:
        'Are you sure you want to delete this coverage code? This action cannot be undone.',
      cancel: 'Cancel',
      confirmDelete: 'Delete Coverage Code',
      errors: {
        listLoad: 'Failed to load coverage codes. Please try again.',
        detailLoad: 'Failed to load coverage code details. Please try again.',
      },
    },
  },
  table: {
    emptyValue: '-',
    columns: {
      code: 'Code',
      name: 'Name',
      carrier: 'Carrier',
      description: 'Description',
      view: 'View',
      edit: 'Edit',
      delete: 'Delete',
    },
    viewAria: (code: string) => `View ${code}`,
    editAria: (code: string) => `Edit ${code}`,
    deleteAria: (code: string) => `Delete ${code}`,
  },
  form: {
    kicker: 'Site Manager',
    defaultTitle: 'New Coverage Code',
    titles: {
      create: 'Create Coverage Code',
      edit: 'Edit Coverage Code',
    },
    saveLabels: {
      create: 'Save',
      edit: 'Save Changes',
    },
    navigation: {
      back: 'Back',
      next: 'Next',
    },
    steps: [
      { id: 'general', label: 'General', index: 0 },
      { id: 'processing', label: 'Processing', index: 1 },
      { id: 'notes', label: 'Notes', index: 2 },
      { id: 'review', label: 'Review', index: 3 },
    ],
    carriersLoadError: 'Failed to load carriers. Please refresh.',
    coverageClassesLoadError: 'Failed to load coverage classes. Please refresh.',
    coverageTypesLoadError: 'Failed to load coverage types. Please refresh.',
    loadingMoreCarriers: 'Loading more carriers...',
    validationSummary: 'Please fix the highlighted fields before saving.',
    actions: {
      back: 'Back',
      save: 'Save',
    },
  },
  generalStep: {
    codeLabel: 'Coverage Code',
    codePlaceholder: 'Enter coverage code',
    nameLabel: 'Name',
    namePlaceholder: 'Enter coverage name',
    carrierLabel: 'Carrier',
    carrierLoadingPlaceholder: 'Loading carriers...',
    carrierSelectPlaceholder: 'Select a carrier...',
    coverageClassLabel: 'Coverage Class',
    coverageClassLoadingPlaceholder: 'Loading classes...',
    coverageClassSelectPlaceholder: 'Select a coverage class...',
    coverageTypeLabel: 'Coverage Type',
    coverageTypeLoadingPlaceholder: 'Loading types...',
    coverageTypeSelectPlaceholder: 'Select a coverage type...',
  },
  processingStep: {
    combinationForBillLabel: 'Billing Combination',
    combinationForBillPlaceholder: 'Enter combination for bill',
    combinationForReportsLabel: 'Reporting Combination',
    combinationForReportsPlaceholder: 'Enter combination for reports',
    useForBillLabel: 'Use for Billing',
    descriptionLabel: 'Long Description',
    descriptionPlaceholder: 'Enter full description',
    shortDescriptionLabel: 'Short Description',
    shortDescriptionPlaceholder: 'Enter short description',
    invoiceGroupLabel: 'Invoice Group',
    invoiceGroupPlaceholder: 'Enter invoice group',
  },
  notesStep: {
    heading: 'Important Notes',
    description: 'Add any optional administrative notes for this coverage code.',
    placeholder: 'Paragraph describing any additional information needed',
  },
  reviewStep: {
    heading: 'Review & Save',
    description: 'Confirm all details before saving the coverage code.',
    emptyValue: '—',
    yes: 'Yes',
    no: 'No',
    sections: {
      general: 'General Information',
      processing: 'Processing Details',
      notes: 'Administrative Notes',
    },
    fields: {
      code: 'Code',
      name: 'Name',
      carrier: 'Carrier',
      coverageClass: 'Coverage Class',
      coverageType: 'Coverage Type',
      combinationForBill: 'Combination for Bill',
      combinationForReports: 'Combination for Reports',
      useForBill: 'Use for Bill',
      description: 'Description',
      shortDescription: 'Short Description',
      invoiceGroup: 'Invoice Group',
      notes: 'Administrative Notes',
    },
  },
  validation: {
    codeRequired: 'Code is required',
    codeMax: 'Code must be 50 characters or fewer',
    nameRequired: 'Name is required',
    nameMax: 'Name must be 100 characters or fewer',
    carrierRequired: 'Carrier is required',
    coverageClassRequired: 'Coverage Class is required',
    combinationForBillRequired: 'Combination for Bill is required',
    combinationForBillMax: 'Combination for Bill must be 100 characters or fewer',
    combinationForReportsRequired: 'Combination for Reports is required',
    combinationForReportsMax:
      'Combination for Reports must be 100 characters or fewer',
    descriptionRequired: 'Description is required',
    descriptionMax: 'Description must be 250 characters or fewer',
    shortDescriptionRequired: 'Short description is required',
    shortDescriptionMax: 'Short description must be 100 characters or fewer',
  },
  toasts: {
    createSuccess: 'Coverage code created successfully!',
    createError: 'Failed to create coverage code. Please try again.',
    updateSuccess: 'Coverage code updated successfully!',
    updateError: 'Failed to update coverage code. Please try again.',
    deleteSuccess: 'Coverage code deleted successfully!',
    deleteError: 'Failed to delete coverage code. Please try again.',
  },
} as const
