export const COVERAGE_CODE_CONTENT = {
  list: {
    kicker: 'Site Manager',
    title: 'Coverage Codes',
    description:
      'Manage coverage code records and pricing rules with reusable TanStack Table columns, server-side pagination, and action controls.',
    addButton: 'New Coverage Code',
    loadErrorFallback: 'Unable to load coverage codes. Please try again.',
    retry: 'Retry',
  },
  pages: {
    new: {
      formTitle: 'New Coverage Code',
    },
  },
  table: {
    emptyValue: '-',
    columns: {
      code: 'Code',
      description: 'Description',
      edit: 'Edit',
      delete: 'Delete',
    },
    editAria: (code: string) => `Edit ${code}`,
    deleteAria: (code: string) => `Delete ${code}`,
  },
  form: {
    defaultTitle: 'New Coverage Code',
    labels: {
      code: 'Code',
      name: 'Name',
      carrier: 'Carrier',
      coverageClass: 'Coverage Class',
      combinationForBill: 'Combination for Bill',
      useForBill: 'Use for Bill',
      combinationForReports: 'Combination for Reports',
      description: 'Description',
      shortDescription: 'Short description',
    },
    placeholders: {
      code: 'Enter coverage code',
      name: 'Enter coverage name',
      carrierLoading: 'Loading...',
      carrierSelect: 'Select a carrier...',
      coverageClassLoading: 'Loading...',
      coverageClassSelect: 'Select a coverage class...',
      combinationForBill: 'Enter combination for bill',
      combinationForReports: 'Enter combination for reports',
      description: 'Enter full description',
      shortDescription: 'Enter short description',
    },
    carriersLoadError: 'Failed to load carriers. Please refresh.',
    coverageClassesLoadError: 'Failed to load coverage classes. Please refresh.',
    loadingMoreCarriers: 'Loading more carriers...',
    validationSummary: 'Please fix the highlighted fields before saving.',
    actions: {
      back: 'Back',
      save: 'Save',
    },
  },
  validation: {
    codeRequired: 'Code is required',
    codeMax: 'Code must be 50 characters or fewer',
    nameRequired: 'Name is required',
    nameMax: 'Name must be 100 characters or fewer',
    carrierRequired: 'Carrier is required',
    coverageClassRequired: 'Coverage Class is required',
    combinationForBillRequired: 'Combination for Bill is required',
    combinationForBillMax: 'Combination for Bill must be 100 characters or fewer',
    combinationForReportsRequired: 'Combination for Reports is required',
    combinationForReportsMax:
      'Combination for Reports must be 100 characters or fewer',
    descriptionRequired: 'Description is required',
    descriptionMax: 'Description must be 250 characters or fewer',
    shortDescriptionRequired: 'Short description is required',
    shortDescriptionMax: 'Short description must be 100 characters or fewer',
  },
  toasts: {
    createSuccess: 'Coverage code created successfully!',
    createError: 'Failed to create coverage code. Please try again.',
  },
} as const
