export const EMPLOYER_CONTENT = {
  pages: {
    employerAndUsers: {
      kicker: 'Administration',
      title: 'Employer & Users',
      chooseHeading: 'Select a Task:',
      cards: {
        employerSetup: {
          title: 'Employer Setup',
          description: 'Manage Employers and Employer Groups',
        },
        usersSetup: {
          title: 'Users Setup',
          description: 'Manage users that have access to the AMCA Platform',
        },
      },
    },
    employerSetup: {
      kicker: 'Administration',
      title: 'Employer Setup',
      chooseHeading: 'Select a Task:',
      cards: {
        new: {
          title: 'New Employer Setup',
          description: 'Add a New Employer to a Parent Company',
        },
        update: {
          title: 'Update Current Employer',
          description: 'Update available Employers',
        },
      },
    },
    usersSetup: {
      kicker: 'Administration',
      title: 'Users Setup',
      description: 'Manage users that have access to the AMCA Platform.',
    },
    new: {
      formTitle: 'New Employer',
    },
    edit: {
      kicker: 'Administration',
      title: 'Update Current Employer',
      description:
        'Select an employer to load its details, then update using the same guided steps as new setup.',
      selectLabel: 'Select Employer',
      selectCardDescription:
        'Search by employer name and choose to view or edit.',
      selectPlaceholder: 'Choose an employer',
      selectLoadingPlaceholder: 'Loading employers...',
      selectSearchPlaceholder: 'Search employers...',
      selectNoResults: 'No employers match your search.',
      selectPrompt: 'Choose an employer from the dropdown to continue.',
      emptyStateTitle: 'Ready when you are',
      editingLabel: 'Editing:',
      loadingDetails: 'Loading employer details...',
      searchPlaceholder: 'Search by employer name...',
      searchButton: 'Search',
      clearButton: 'Clear',
      viewTitle: 'Employer Information',
      viewDescription:
        'View complete details for the selected employer record.',
      tabs: {
        general: 'General',
        plan: 'Plan',
      },
      deleteButton: 'Delete',
      backButton: 'Back',
      editButton: 'Edit',
      editGeneralButton: 'Edit General',
      editPlanButton: 'Edit Plan',
      confirmDeleteTitle: 'Delete Employer',
      confirmDeletePrompt:
        'Are you sure you want to delete this employer? This action cannot be undone.',
      cancel: 'Cancel',
      confirmDelete: 'Delete Employer',
      errors: {
        listLoad: 'Failed to load employers. Please try again.',
        detailLoad: 'Failed to load employer details. Please try again.',
      },
    },
    plansList: {
      kicker: 'Administration',
      title: 'Employer Plans',
      description: 'Manage plans and rates configured for this employer group.',
      addPlanButton: 'Add Plan',
      backButton: 'Back',
      emptyValue: '-',
      columns: {
        plan: 'PLAN NAME',
        coverageCode: 'COVERAGE CODE',
        option: 'OPTION',
        groupNumber: 'GROUP NUMBER',
        action: 'ACTION',
      },
      editAction: 'Edit',
      editAria: (name: string) => `Edit plan ${name}`,
      emptyTable: 'No plans found for this employer. Click Add Plan above to add one.',
      loading: 'Loading employer plans...',
      error: 'Failed to load employer plans. Please try again.',
      retry: 'Retry',
      modal: {
        titleAdd: 'Add Employer Plan',
        titleEdit: 'Edit Employer Plan',
        descriptionAdd:
          'Configure a plan, group numbers, and rates for this employer group.',
        descriptionEdit:
          'Update plan details, group numbers, and rates for this employer group.',
        tabs: {
          planDetails: 'Plan Details',
          rates: 'Rates',
        },
        saveButton: 'Save Plan',
        savingButton: 'Saving...',
        cancelButton: 'Cancel',
      },
    },
  },
  filters: {
    allParentCompanies: 'All Parent Companies',
    parentCompanyLabel: 'Parent Company',
    clearFilters: 'Clear Filters',
    loadingMore: 'Loading more...',
    parentCompanyPlaceholder: 'Filter by parent company...',
  },
  table: {
    emptyValue: '-',
    columns: {
      name: 'Name',
      parentCompany: 'Parent Company',
      view: 'View',
      edit: 'Edit',
      delete: 'Delete',
    },
    viewAria: (name: string) => `View ${name}`,
    editAria: (name: string) => `Edit ${name}`,
    deleteAria: (name: string) => `Delete ${name}`,
  },
  form: {
    kicker: '',
    defaultTitle: 'New Employer',
    titles: {
      create: 'Create Employer',
      edit: 'Edit Employer',
      editGeneral: 'Edit Employer (General)',
      editPlan: 'Edit Employer Plan',
      addPlan: 'Add Employer Plan',
    },
    saveLabels: {
      create: 'Save',
      edit: 'Save Changes',
    },
    navigation: {
      back: 'Back',
      next: 'Next',
    },
    steps: [
      { id: 'general', label: 'General', index: 0 },
      { id: 'contact', label: 'Contact', index: 1 },
      { id: 'configuration', label: 'Configuration', index: 2 },
      { id: 'carriers', label: 'Carriers', index: 3 },
      { id: 'notes', label: 'Notes', index: 4 },
      { id: 'plan', label: 'Plan', index: 5 },
      { id: 'rate', label: 'Rate', index: 6 },
      { id: 'review', label: 'Review', index: 7 },
    ],
    generalSteps: [
      { id: 'general', label: 'General', index: 0 },
      { id: 'contact', label: 'Contact', index: 1 },
      { id: 'configuration', label: 'Configuration', index: 2 },
      { id: 'carriers', label: 'Carriers', index: 3 },
      { id: 'notes', label: 'Notes', index: 4 },
      { id: 'review', label: 'Review', index: 5 },
    ],
    planSteps: [
      { id: 'plan', label: 'Plan', index: 0 },
      { id: 'rate', label: 'Rate', index: 1 },
      { id: 'review', label: 'Review', index: 2 },
    ],
    validationSummary: 'Please fix the highlighted fields before saving.',
  },
  generalStep: {
    heading: 'General Information',
    description: 'Enter basic information and address details for this employer.',
    nameLabel: 'Employer Name',
    namePlaceholder: 'Enter employer name',
    parentCompanyLabel: 'Parent Company Name',
    parentCompanyLoadingPlaceholder: 'Loading parent companies...',
    parentCompanySelectPlaceholder: 'Select a parent company',
    additionalDetailsHeading: 'Employer Address',
    address1Label: 'Address 1',
    address1Placeholder: 'Street Address or P.O Box',
    address2Label: 'Address 2',
    address2Placeholder: 'Enter address line 2',
    cityLabel: 'City',
    cityPlaceholder: 'City',
    stateLabel: 'State',
    stateLoadingPlaceholder: 'Loading states...',
    stateSelectPlaceholder: 'State',
    stateLoadError: 'Failed to load states. Please refresh.',
    zipCodeLabel: 'ZIP Code',
    zipCodePlaceholder: '5-digit Zip',
  },
  contactStep: {
    heading: 'PRIMARY CONTACT INFORMATION',
    description: 'Enter the main contact details for this employer.',
    firstNameLabel: 'First Name',
    firstNamePlaceholder: 'ex. John',
    lastNameLabel: 'Last Name',
    lastNamePlaceholder: 'ex. Doe',
    titleLabel: 'Title',
    titlePlaceholder: 'ex. HR Manager',
    phoneLabel: 'Phone Number',
    phonePlaceholder: '(000) 000-0000',
    faxLabel: 'Fax',
    faxPlaceholder: '(000) 000-0000',
    emailLabel: 'Email',
    emailPlaceholder: 'ex. john.doe@example.com',
  },
  configurationStep: {
    heading: 'Configuration',
    description: 'Enter group numbers, status, and policy options.',
    groupNumberLabel: 'Group Number',
    groupNumberPlaceholder: 'Enter group number',
    policyNumberLabel: 'Policy Number',
    policyNumberPlaceholder: 'Enter policy number',
    tpacNumberLabel: 'TPAC Number',
    tpacNumberPlaceholder: 'Enter TPAC number',
    monthlyAdminFeeLabel: 'Monthly Admin Fee',
    monthlyAdminFeePlaceholder: 'ex. 1500',
    statusLabel: 'Status',
    statusActive: 'Active',
    statusInactive: 'Inactive',
    usePaperInvoiceLabel: 'Use Paper Invoice',
    allowCobraLabel: 'Allow Cobra',
    exactDayLabel: 'Exact Day?',
    renewalDateLabel: 'Renewal Date',
    renewalDatePlaceholder: 'Select renewal date...',
    initialNotificationStartOnLabel: 'Initial Notification Start On',
    initialNotificationStartOnPlaceholder: 'Select initial notification date...',
  },
  carriersStep: {
    heading: 'Carrier Selection',
    description: 'Choose carriers associated with this employer.',
    loading: 'Loading carriers...',
    loadError: 'Failed to load carriers. Please refresh the page.',
    availableHeading: 'Available Carriers',
    shownCount: '{{count}} shown',
    searchAvailablePlaceholder: 'Search available carriers...',
    noSearchMatches: 'No carriers match your search.',
    loadingMore: 'Loading more carriers...',
    selectedHeading: 'Selected Carriers',
    searchSelectedPlaceholder: 'Search selected carriers...',
    noneSelected: 'No carriers selected yet.',
    noSelectedSearchMatches: 'No selected carriers match your search.',
    actionSelect: 'Select',
    actionSelected: 'Selected',
    actionRemove: 'Remove',
    hintLeft:
      'Select carriers from the left panel. Already selected carriers stay visible but disabled.',
    hintRight: 'Remove carriers from the right panel to deselect them.',
  },
  notesStep: {
    heading: 'EMPLOYER NOTES',
    titleLabel: 'Title',
    titlePlaceholder: 'Enter title for notes',
    notesLabel: 'Administrative Notes',
    notesPlaceholder: '(Optional) Add information for other administrators.',
  },
  planStep: {
    heading: 'Plan',
    description: 'Select a plan and specify group and broker details for this employer.',
    planLabel: 'Plan',
    planPlaceholder: 'Select a plan...',
    planLoadingPlaceholder: 'Loading plans...',
    groupNumberLabel: 'Group Number',
    groupNumberPlaceholder: 'Enter group number',
    billerAccountNumberLabel: 'Biller Account Number',
    billerAccountNumberPlaceholder: 'Enter biller account number',
    customerNumberLabel: 'Customer Number',
    customerNumberPlaceholder: 'Enter customer number',
    brokerCodeLabel: 'Broker Code',
    brokerCodePlaceholder: 'Select broker code...',
    brokerCodeLoadingPlaceholder: 'Loading broker codes...',
    isActiveLabel: 'Is Active',
    addButton: 'Add Plan',
    updateButton: 'Update Plan',
    cancelEditButton: 'Cancel',
    addedPlanHeading: 'ADDED PLAN',
    clickRowToEditHint: 'Click a row to edit its values',
    tableColumns: {
      plan: 'PLAN',
      groupNumber: 'GROUP NUMBER',
      billerAccount: 'BILLER ACCOUNT',
      customerNumber: 'CUSTOMER NUMBER',
      brokerCode: 'BROKER CODE',
      status: 'STATUS',
      action: 'ACTION',
    },
    deleteAria: 'Delete plan',
    activeStatus: 'Active',
    inactiveStatus: 'Inactive',
    emptyTable: 'No plan added yet. Fill in the fields above and click Add Plan.',
  },
  rateStep: {
    heading: 'RATES',
    description: 'Configure effective date and rate tiers for this employer plan.',
    selectPlanLabel: 'Plan',
    selectPlanPlaceholder: 'Select a plan...',
    selectPlanHint: 'Choose a plan to view and add its rate tiers.',
    noPlanSelectedHint: 'Please select a plan from the dropdown above to configure its rates.',
    ratesForPlanHeading: 'Rates for Selected Plan',
    effectiveDateLabel: 'Effective Date',
    effectiveDatePlaceholder: 'Pick a date',
    individualLabel: 'Individual',
    individualPlaceholder: '0.00',
    parentChildLabel: 'Parent/Child',
    parentChildPlaceholder: '0.00',
    parentChildrenLabel: 'Parent/Children',
    parentChildrenPlaceholder: '0.00',
    memberSpouseLabel: 'Member Spouse',
    memberSpousePlaceholder: '0.00',
    familyLabel: 'Family',
    familyPlaceholder: '0.00',
    addButton: 'Add Rate',
    updateButton: 'Update Rate',
    cancelEditButton: 'Cancel',
    addedRatesHeading: 'ADDED RATES',
    clickRowToEditHint: 'Click a row to edit its values',
    tableColumns: {
      effectiveDate: 'EFFECTIVE DATE',
      individual: 'INDIVIDUAL',
      parentChild: 'PARENT/CHILD',
      parentChildren: 'PARENT/CHILDREN',
      memberSpouse: 'MEMBER SPOUSE',
      family: 'FAMILY',
      action: 'ACTION',
    },
    deleteAria: 'Delete rate',
    emptyTable: 'No rates added for this plan yet. Select an effective date and enter rates above.',
    allPlansMustHaveRates: 'Every added plan must have at least one rate configured.',
  },
  reviewStep: {
    heading: 'Review & Save',
    description: 'Confirm all details before saving the employer.',
    emptyValue: '—',
    yes: 'Yes',
    no: 'No',
    sections: {
      general: 'General Information',
      primaryAddress: 'Employer Address',
      contact: 'Primary Contact',
      configuration: 'Configuration',
      carriers: 'Selected Carriers',
      notes: 'Administrative Notes',
      plan: 'Plan Details',
      rates: 'Plan Rates',
      plansAndRates: 'Plans & Rates',
    },
    fields: {
      name: 'Employer Name',
      parentCompany: 'Parent Company',
      address1: 'Address 1',
      address2: 'Address 2',
      city: 'City',
      state: 'State',
      zip: 'ZIP Code',
      contactFirstName: 'First Name',
      contactLastName: 'Last Name',
      contactTitle: 'Title',
      phone: 'Phone Number',
      fax: 'Fax',
      email: 'Email',
      groupNumber: 'Group Number',
      policyNumber: 'Policy Number',
      tpacNumber: 'TPAC Number',
      monthlyAdminFee: 'Monthly Admin Fee',
      status: 'Status',
      isPaper: 'Use Paper Invoice',
      allowCobra: 'Allow Cobra',
      isPano: 'Exact Day?',
      renewalDate: 'Renewal Date',
      initialNotificationStartOn: 'Initial Notification Start On',
      notesTitle: 'Notes Title',
      notes: 'Notes',
      plan: 'Plan',
      planGroupNumber: 'Group Number',
      billerAccountNumber: 'Biller Account',
      customerNumber: 'Customer Number',
      brokerCode: 'Broker Code',
      isActive: 'Is Active',
      effectiveDate: 'Effective Date',
      individual: 'Individual',
      parentChild: 'Parent/Child',
      parentChildren: 'Parent/Children',
      memberSpouse: 'Member Spouse',
      family: 'Family',
    },
    noCarriersSelected: 'No carriers selected.',
    noPlansConfigured: 'No plans configured.',
    noRatesConfigured: 'No rates configured.',
  },
  toasts: {
    createSuccess: 'Employer created successfully!',
    createError: 'Failed to create employer. Please try again.',
    updateSuccess: 'Employer updated successfully!',
    updateError: 'Failed to update employer. Please try again.',
    createPlanSuccess: 'Employer plan added successfully!',
    createPlanError: 'Failed to add employer plan. Please try again.',
    updatePlanSuccess: 'Employer plan updated successfully!',
    updatePlanError: 'Failed to update employer plan. Please try again.',
    deleteSuccess: 'Employer deleted successfully!',
    deleteError: 'Failed to delete employer. Please try again.',
  },
  validation: {
    nameRequired: 'Employer Name is required',
    nameMax: 'Employer Name must be 100 characters or fewer',
    parentCompanyRequired: 'Parent Company is required',
    address1Required: 'Address 1 is required',
    addressMax: 'Address must be 200 characters or fewer',
    cityRequired: 'City is required',
    cityMax: 'City must be 100 characters or fewer',
    cityLetters: 'City must contain only letters',
    zipRequired: 'ZIP Code is required',
    zipInvalid: 'ZIP Code must be exactly 5 digits',
    contactFirstRequired: 'First Name is required',
    contactFirstMax: 'First name must be 50 characters or fewer',
    contactFirstLetters: 'First name must contain only letters',
    contactLastRequired: 'Last Name is required',
    contactLastMax: 'Last name must be 50 characters or fewer',
    contactLastLetters: 'Last name must contain only letters',
    contactTitleMax: 'Contact Title must be 100 characters or fewer',
    phoneInvalid: 'Enter a valid phone number — (___) ___-____',
    faxInvalid: 'Enter a valid fax number — (___) ___-____',
    emailInvalid: 'Enter a valid email address',
    emailMax: 'Email must be 254 characters or fewer',

    groupNumberRequired: 'Group Number is required',
    groupNumberMax: 'Group Number must be 10 characters or fewer',
    policyNumberMax: 'Policy Number must be 50 characters or fewer',
    tpacNumberMax: 'TPAC Number must be 3 characters or fewer',
    monthlyAdminFeeMax: 'Monthly Admin Fee must be 16 digits or fewer',
    notesTitleMax: 'Notes Title must be 200 characters or fewer',
    notesMax: 'Notes must be 2000 characters or fewer',
    cgnCustomerNumberMax: 'Customer Number must be 10 characters or fewer',

    planRequired: 'Plan is required',
    cgnGroupNumberRequired: 'Group Number is required',
    billerAccountNumberRequired: 'Biller Account Number is required',
    effectiveDateRequired: 'Effective Date is required',
    individualRequired: 'Individual rate is required',
    parentChildRequired: 'Parent/Child rate is required',
    parentChildrenRequired: 'Parent/Children rate is required',
    memberSpouseRequired: 'Member Spouse rate is required',
    familyRequired: 'Family rate is required',
    planRequiresAtLeastOne: 'Please add a plan before proceeding.',
    rateRequiresAtLeastOne: 'Please add at least one rate before proceeding to review.',
  },
} as const

