export const EMPLOYER_CONTENT = {
  pages: {
    index: {
      kicker: 'Administration',
      title: 'Update Employers',
      description:
        'Select an action below to set up a new employer or manage existing employers.',
      chooseHeading: 'Please Choose',
      cards: {
        new: {
          title: 'New Employer',
          description: 'Guided Employer Setup',
        },
        update: {
          title: 'Update Current Employer',
          description: 'Update Available Employers',
        },
      },
    },
    new: {
      formTitle: 'New Employer',
    },
    edit: {
      kicker: 'Administration',
      title: 'Employer Edit',
      description:
        'Select an employer to load its details, then update using the same guided steps as new setup.',
      selectLabel: 'Select Employer',
      selectCardDescription:
        'Search by employer name and choose to view or edit.',
      selectPlaceholder: 'Choose an employer',
      selectLoadingPlaceholder: 'Loading employers...',
      selectSearchPlaceholder: 'Search employers...',
      selectNoResults: 'No employers match your search.',
      selectPrompt: 'Choose an employer from the dropdown to continue.',
      emptyStateTitle: 'Ready when you are',
      editingLabel: 'Editing:',
      loadingDetails: 'Loading employer details...',
      searchPlaceholder: 'Search by employer name...',
      searchButton: 'Search',
      clearButton: 'Clear',
      viewTitle: 'Employer Information',
      viewDescription:
        'View complete details for the selected employer record.',
      deleteButton: 'Delete',
      backButton: 'Back',
      editButton: 'Edit',
      confirmDeleteTitle: 'Delete Employer',
      confirmDeletePrompt:
        'Are you sure you want to delete this employer? This action cannot be undone.',
      cancel: 'Cancel',
      confirmDelete: 'Delete Employer',
      errors: {
        listLoad: 'Failed to load employers. Please try again.',
        detailLoad: 'Failed to load employer details. Please try again.',
      },
    },
  },
  table: {
    emptyValue: '-',
    columns: {
      name: 'Name',
      parentCompany: 'Parent Company',
      view: 'View',
      edit: 'Edit',
      delete: 'Delete',
    },
    viewAria: (name: string) => `View ${name}`,
    editAria: (name: string) => `Edit ${name}`,
    deleteAria: (name: string) => `Delete ${name}`,
  },
  form: {
    kicker: 'Site Manager',
    defaultTitle: 'New Employer',
    titles: {
      create: 'Create Employer',
      edit: 'Edit Employer',
    },
    saveLabels: {
      create: 'Save',
      edit: 'Save Changes',
    },
    navigation: {
      back: 'Back',
      next: 'Next',
    },
    steps: [
      { id: 'general', label: 'General', index: 0 },
      { id: 'contact', label: 'Contact', index: 1 },
      { id: 'carriers', label: 'Carriers', index: 2 },
      { id: 'companyGroup', label: 'Carrier Group Number', index: 3 },
      { id: 'notes', label: 'Notes', index: 4 },
      { id: 'review', label: 'Review', index: 5 },
    ],
    validationSummary: 'Please fix the highlighted fields before saving.',
  },
  generalStep: {
    heading: 'General Information',
    description: 'Enter basic information and primary address details for this employer.',
    nameLabel: 'Employer Name',
    namePlaceholder: 'Enter employer name',
    parentCompanyLabel: 'Parent Company Name',
    parentCompanyLoadingPlaceholder: 'Loading parent companies...',
    parentCompanySelectPlaceholder: 'Select a parent company',
    additionalDetailsHeading: 'Additional Details',
    address1Label: 'Address 1',
    address1Placeholder: 'Enter street address line 1',
    address2Label: 'Address 2',
    address2Placeholder: 'Enter suite, unit, or address line 2',
    cityLabel: 'City',
    cityPlaceholder: 'Enter city',
    stateLabel: 'State',
    stateLoadingPlaceholder: 'Loading states...',
    stateSelectPlaceholder: 'Select a state',
    stateLoadError: 'Failed to load states. Please refresh.',
    zipCodeLabel: 'ZIP Code',
    zipCodePlaceholder: 'Enter ZIP code',
  },
  contactStep: {
    heading: 'Primary Contact Information',
    description: 'Enter the main contact details for this employer.',
    firstNameLabel: 'Contact First Name',
    firstNamePlaceholder: 'ex. John',
    lastNameLabel: 'Contact Last Name',
    lastNamePlaceholder: 'ex. Doe',
    titleLabel: 'Title',
    titlePlaceholder: 'ex. HR Manager',
    phoneLabel: 'Phone Number',
    phonePlaceholder: '(___) ___-____',
    faxLabel: 'Fax Number',
    faxPlaceholder: '(___) ___-____',
    emailLabel: 'Email Address',
    emailPlaceholder: 'ex. john.doe@example.com',
  },
  carriersStep: {
    heading: 'Carrier Selection',
    description: 'Choose carriers associated with this employer.',
    loading: 'Loading carriers...',
    loadError: 'Failed to load carriers. Please refresh the page.',
    availableHeading: 'Available Carriers',
    shownCount: '{{count}} shown',
    searchAvailablePlaceholder: 'Search available carriers...',
    noSearchMatches: 'No carriers match your search.',
    loadingMore: 'Loading more carriers...',
    selectedHeading: 'Selected Carriers',
    searchSelectedPlaceholder: 'Search selected carriers...',
    noneSelected: 'No carriers selected yet.',
    noSelectedSearchMatches: 'No selected carriers match your search.',
    actionSelect: 'Select',
    actionSelected: 'Selected',
    actionRemove: 'Remove',
    hintLeft:
      'Select carriers from the left panel. Already selected carriers stay visible but disabled.',
    hintRight: 'Remove carriers from the right panel to deselect them.',
  },
  companyGroupStep: {
    heading: 'Company Group Details',
    description: 'Enter carrier group numbers, status, and policy options.',
    groupNumberLabel: 'Group Number',
    groupNumberPlaceholder: 'Enter group number',
    policyNumberLabel: 'Policy Number',
    policyNumberPlaceholder: 'Enter policy number',
    tpacNumberLabel: 'TPAC Number',
    tpacNumberPlaceholder: 'Enter TPAC number',
    monthlyAdminFeeLabel: 'Monthly Admin Fee',
    monthlyAdminFeePlaceholder: 'ex. 1500',
    statusLabel: 'Status',
    statusActive: 'Active',
    statusInactive: 'Inactive',
    usePaperInvoiceLabel: 'Use Paper Invoice',
    allowCobraLabel: 'Allow Cobra',
    exactDayLabel: 'Exact Day?',
    renewalDateLabel: 'Renewal Date',
    initialNotificationStartOnLabel: 'Initial Notification Start On',
  },
  notesStep: {
    heading: 'Administrative Notes',
    description: 'Add any optional title or administrative notes for this employer.',
    titleLabel: 'Title',
    titlePlaceholder: 'Enter title for notes',
    notesLabel: 'Notes',
    notesPlaceholder: 'Paragraph describing any additional information needed...',
  },
  reviewStep: {
    heading: 'Review & Save',
    description: 'Confirm all details before saving the employer.',
    emptyValue: '—',
    yes: 'Yes',
    no: 'No',
    sections: {
      general: 'General Information',
      primaryAddress: 'Primary Address',
      contact: 'Primary Contact',
      carriers: 'Selected Carriers',
      groupDetails: 'Company Group Details',
      notes: 'Administrative Notes',
    },
    fields: {
      name: 'Employer Name',
      parentCompany: 'Parent Company',
      address1: 'Address 1',
      address2: 'Address 2',
      city: 'City',
      state: 'State',
      zip: 'ZIP Code',
      contactFirstName: 'First Name',
      contactLastName: 'Last Name',
      contactTitle: 'Title',
      phone: 'Phone Number',
      fax: 'Fax Number',
      email: 'Email Address',
      groupNumber: 'Group Number',
      policyNumber: 'Policy Number',
      tpacNumber: 'TPAC Number',
      monthlyAdminFee: 'Monthly Admin Fee',
      status: 'Status',
      isPaper: 'Use Paper Invoice',
      allowCobra: 'Allow Cobra',
      isPano: 'Exact Day?',
      renewalDate: 'Renewal Date',
      initialNotificationStartOn: 'Initial Notification Start On',
      notesTitle: 'Notes Title',
      notes: 'Notes',
    },
    noCarriersSelected: 'No carriers selected.',
  },
  toasts: {
    createSuccess: 'Employer created successfully!',
    createError: 'Failed to create employer. Please try again.',
    updateSuccess: 'Employer updated successfully!',
    updateError: 'Failed to update employer. Please try again.',
    deleteSuccess: 'Employer deleted successfully!',
    deleteError: 'Failed to delete employer. Please try again.',
  },
} as const
