import type { ParentCompanyContent } from '#/types/parent-company-content.ts'

export type { ParentCompanyContent } from '#/types/parent-company-content.ts'

export const PARENT_COMPANY_CONTENT = {
  pages: {
    index: {
      kicker: 'Administration',
      title: 'Parent Company Setup',
      description:
        '',
      chooseHeading: 'Select a task:',
      cards: {
        newSetup: {
          title: 'New Parent Setup',
          description: 'Guided Parent Company Setup',
        },
        update: {
          title: 'Update Current Parent Companies',
          description: 'Update Available Parent Companies',
        },
      },
    },
    edit: {
      kicker: 'Administration',
      title: 'Update Current Parent Company',
      description:
        'Select a parent company to load its details, then update using the same guided steps as new setup.',
      selectLabel: 'Select Parent Company',
      selectCardDescription:
        'Search by parent company name and choose to view or edit.',
      selectPlaceholder: 'Choose a parent company',
      selectLoadingPlaceholder: 'Loading parent companies...',
      selectSearchPlaceholder: 'Search parent companies...',
      selectNoResults: 'No parent companies match your search.',
      selectPrompt: 'Choose a parent company from the dropdown to continue.',
      emptyStateTitle: 'Ready when you are',
      editingLabel: 'Editing:',
      loadingDetails: 'Loading parent company details...',
      searchPlaceholder: 'Search by parent company name',
      searchButton: 'Search',
      clearButton: 'Clear',
      viewTitle: 'Parent Company Information',
      viewDescription:
        'View complete details for the selected parent company record.',
      deleteButton: 'Delete',
      backButton: 'Back',
      editButton: 'Edit',
      confirmDeleteTitle: 'Delete Parent Company',
      confirmDeletePrompt:
        'Are you sure you want to delete this parent company? This action cannot be undone.',
      cancel: 'Cancel',
      confirmDelete: 'Delete Parent Company',
      errors: {
        listLoad: 'Failed to load parent companies. Please try again.',
        detailLoad: 'Failed to load parent company details. Please try again.',
      },
    },
  },
  table: {
    emptyValue: '-',
    columns: {
      name: 'Name',
      contactName: 'Contact Name',
      email: 'Email',
      view: 'View',
      edit: 'Edit',
      delete: 'Delete',
    },
    viewAria: (name: string) => `View ${name}`,
    editAria: (name: string) => `Edit ${name}`,
    deleteAria: (name: string) => `Delete ${name}`,
  },
  form: {
    kicker: '',
    titles: {
      create: 'Create Parent Company',
      edit: 'Edit Parent Company',
    },
    saveLabels: {
      create: 'Save',
      edit: 'Save Changes',
    },
    navigation: {
      back: 'Back',
      next: 'Next',
    },
    validationSummary: 'Please fix the highlighted fields before saving.',
    steps: [
      { id: 'general', label: 'General', index: 0 },
      { id: 'contact', label: 'Contact', index: 1 },
      { id: 'carriers', label: 'Carriers', index: 2 },
      { id: 'notes', label: 'Notes', index: 3 },
      { id: 'review', label: 'Review', index: 4 },
    ],
  },
  generalStep: {
    heading: 'GENERAL INFORMATION',
    nameLabel: 'Parent Company Name',
    namePlaceholder: 'Enter parent company name',
    fullnameLabel: 'Full Name',
    fullnamePlaceholder: 'Enter full name',
    additionalDetailsHeading: 'Parent Company Address',
    primaryAddressHeading: 'Parent Company Address',
    address1Label: 'Address 1',
    address1Placeholder: 'Street Address or P.O Box',
    address2Label: 'Address 2',
    address2Placeholder: 'Enter address line 2',
    cityLabel: 'City',
    cityPlaceholder: 'City',
    stateLabel: 'State',
    stateLoadingPlaceholder: 'Loading...',
    stateSelectPlaceholder: 'State',
    stateLoadError: 'Failed to load states. Please refresh.',
    zipCodeLabel: 'Zip Code',
    zipCodePlaceholder: '5-digit Zip',
  },
  contactStep: {
    heading: 'PRIMARY CONTACT INFORMATION',
    description: '',
    firstNameLabel: 'First Name',
    firstNamePlaceholder: 'ex. John',
    lastNameLabel: 'Last Name',
    lastNamePlaceholder: 'ex. Doe',
    phoneLabel: 'Phone Number',
    phonePlaceholder: '(000) 000-0000',
    alternativePhoneLabel: 'Alternative Phone Number',
    faxLabel: 'Fax',
    emailLabel: 'Email',
    emailPlaceholder: 'ex. john.doe@example.com',
    websiteLabel: 'Website',
    websitePlaceholder: 'ex. https://yourcompany.com',
    allowCobraLabel: 'Allow Cobra',
  },
  carriersStep: {
    heading: 'Carrier Selection',
    description: 'Choose carriers associated with this parent company.',
    loading: 'Loading carriers...',
    loadError: 'Failed to load carriers. Please refresh the page.',
    availableHeading: 'Available Carriers',
    shownCount: '{{count}} shown',
    searchAvailablePlaceholder: 'Search available carriers...',
    noSearchMatches: 'No carriers match your search.',
    loadingMore: 'Loading more carriers...',
    selectedHeading: 'Selected Carriers',
    searchSelectedPlaceholder: 'Search selected carriers...',
    noneSelected: 'No carriers selected yet.',
    noSelectedSearchMatches: 'No selected carriers match your search.',
    actionSelect: 'Select',
    actionSelected: 'Selected',
    actionRemove: 'Remove',
    hintLeft:
      'Select carriers from the left panel. Already selected carriers stay visible but disabled.',
    hintRight: 'Remove carriers from the right panel to deselect them.',
  },
  notesStep: {
    heading: 'PARENT COMPANY NOTES',
    notesLabel: 'Administrative Notes',
    placeholder: '(Optional) Add information for other administrators.',
    allowCobraLabel: 'Allow Cobra',
  },
  reviewStep: {
    heading: 'Review & Save',
    description: 'Confirm all details before saving the parent company.',
    emptyValue: '—',
    sections: {
      general: 'General',
      primaryAddress: 'Parent Company Address',
      contact: 'Contact Information',
      carriers: 'Selected Carriers',
      notes: 'Important Notes',
    },
    fields: {
      name: 'Parent Company Name',
      fullName: 'Full Name',
      address1: 'Address 1',
      address2: 'Address 2',
      city: 'City',
      state: 'State',
      zipCode: 'Zip Code',
      firstName: 'First Name',
      lastName: 'Last Name',
      phone: 'Phone Number',
      alternativePhone: 'Alternative Phone',
      fax: 'Fax',
      email: 'Email',
      website: 'Website',
      allowCobra: 'Allow Cobra',
    },
    noCarriersSelected: 'No carriers selected.',
  },
  validation: {
    contactFirstNameRequired: 'First Name is required',
    contactLastNameRequired: 'Last Name is required',
    contactPhoneRequired: 'Phone Number is required',
    contactPhoneDigits: 'Phone Number must be exactly 10 digits',
    alternativePhoneRequired: 'Alternative Phone Number is required',
    alternativePhoneDigits: 'Alternative Phone Number must be exactly 10 digits',
    faxRequired: 'Fax is required',
    faxDigits: 'Fax must be exactly 10 digits',
    emailRequired: 'Email is required',
    emailInvalid: 'Enter a valid email address',
    nameRequired: 'Parent Company Name is required',
    address1Required: 'Address 1 is required',
    address2Required: 'Address 2 is required',
    cityRequired: 'City is required',
    stateRequired: 'State is required',
    zipRequired: 'Zip Code is required',
    zipDigits: 'Zip Code must be exactly 5 digits',
    duplicateCarriers: 'Duplicate carriers are not allowed',
    fieldRequired: '{{field}} is required',
    fieldTenDigits: '{{field}} must be exactly 10 digits',
  },
  toasts: {
    create: {
      success: 'Parent Company created successfully.',
      error: 'Failed to create parent company. Please try again.',
    },
    update: {
      success: 'Parent Company updated successfully.',
      error: 'Failed to update parent company. Please try again.',
    },
    delete: {
      success: 'Parent Company deleted successfully.',
      error: 'Failed to delete parent company. Please try again.',
    },
  },
} satisfies ParentCompanyContent
