import type { ParentCompanyContent } from '#/types/parent-company-content.ts'

export type { ParentCompanyContent } from '#/types/parent-company-content.ts'

export const PARENT_COMPANY_CONTENT = {
  pages: {
    index: {
      kicker: 'Administration',
      title: 'Update Parent Companies',
      description:
        'Select an action below to set up a new parent company or manage existing parent companies.',
      chooseHeading: 'Please Choose',
      cards: {
        newSetup: {
          title: 'New Parent Setup',
          description: 'Guided Parent Setup',
        },
        update: {
          title: 'Update Current Parent Company',
          description: 'Update Available Parent Companies',
        },
      },
    },
    edit: {
      kicker: 'Administration',
      title: 'Parent Company Edit',
      description:
        'Select a parent company to load its details, then update using the same guided steps as new setup.',
      selectLabel: 'Select Parent Company',
      selectPlaceholder: 'Choose a parent company',
      selectLoadingPlaceholder: 'Loading parent companies...',
      selectSearchPlaceholder: 'Search parent companies...',
      selectNoResults: 'No parent companies match your search.',
      selectPrompt: 'Select a parent company above to begin editing.',
      loadingDetails: 'Loading parent company details...',
      errors: {
        listLoad: 'Failed to load parent companies. Please try again.',
        detailLoad: 'Failed to load parent company details. Please try again.',
      },
    },
  },
  form: {
    kicker: 'Site Manager',
    titles: {
      create: 'Create Parent Company',
      edit: 'Edit Parent Company',
    },
    saveLabels: {
      create: 'Save',
      edit: 'Save Changes',
    },
    navigation: {
      back: 'Back',
      next: 'Next',
    },
    validationSummary: 'Please fix the highlighted fields before saving.',
    steps: [
      { id: 'general', label: 'General', index: 0 },
      { id: 'contact', label: 'Contact', index: 1 },
      { id: 'carriers', label: 'Carriers', index: 2 },
      { id: 'notes', label: 'Notes', index: 3 },
      { id: 'review', label: 'Review', index: 4 },
    ],
  },
  generalStep: {
    nameLabel: 'Parent Company Name',
    namePlaceholder: 'Enter parent company name',
    additionalDetailsHeading: 'Additional Details',
    primaryAddressHeading: 'Primary Address',
    address1Label: 'Address 1',
    address1Placeholder: 'Enter street address',
    address2Label: 'Address 2',
    address2Placeholder: 'Enter suite, unit, or additional address info',
    cityLabel: 'City',
    cityPlaceholder: 'Enter city',
    stateLabel: 'State',
    stateLoadingPlaceholder: 'Loading...',
    stateSelectPlaceholder: 'Select a state',
    stateLoadError: 'Failed to load states. Please refresh.',
    zipCodeLabel: 'Zip Code',
    zipCodePlaceholder: 'Enter zipcode',
  },
  contactStep: {
    heading: 'Primary Contact Information',
    description: 'Enter the main point of contact for this parent company.',
    firstNameLabel: 'Contact First Name',
    firstNamePlaceholder: 'ex. John',
    lastNameLabel: 'Contact Last Name',
    lastNamePlaceholder: 'ex. Doe',
    phoneLabel: 'Contact Phone Number',
    phonePlaceholder: '(000) 000-0000',
    alternativePhoneLabel: 'Alternative Phone Number',
    faxLabel: 'Fax',
    emailLabel: 'Email',
    emailPlaceholder: 'ex. john.doe@example.com',
    websiteLabel: 'Website',
    websitePlaceholder: 'ex. https://yourcompany.com',
  },
  carriersStep: {
    heading: 'Carrier Selection',
    description: 'Choose carriers associated with this parent company.',
    loading: 'Loading carriers...',
    loadError: 'Failed to load carriers. Please refresh the page.',
    availableHeading: 'Available Carriers',
    shownCount: '{{count}} shown',
    searchAvailablePlaceholder: 'Search available carriers...',
    noSearchMatches: 'No carriers match your search.',
    loadingMore: 'Loading more carriers...',
    selectedHeading: 'Selected Carriers',
    searchSelectedPlaceholder: 'Search selected carriers...',
    noneSelected: 'No carriers selected yet.',
    noSelectedSearchMatches: 'No selected carriers match your search.',
    actionSelect: 'Select',
    actionSelected: 'Selected',
    actionRemove: 'Remove',
    hintLeft:
      'Select carriers from the left panel. Already selected carriers stay visible but disabled.',
    hintRight: 'Remove carriers from the right panel to deselect them.',
  },
  notesStep: {
    heading: 'Important Notes',
    description:
      'Add any additional information that should be recorded for this parent company.',
    placeholder: 'Paragraph describing any additional information needed',
  },
  reviewStep: {
    heading: 'Review & Save',
    description: 'Confirm all details before saving the parent company.',
    emptyValue: '—',
    sections: {
      general: 'General',
      primaryAddress: 'Primary Address',
      contact: 'Contact Information',
      carriers: 'Selected Carriers',
      notes: 'Important Notes',
    },
    fields: {
      name: 'Parent Company Name',
      address1: 'Address 1',
      address2: 'Address 2',
      city: 'City',
      state: 'State',
      zipCode: 'Zip Code',
      firstName: 'First Name',
      lastName: 'Last Name',
      phone: 'Phone',
      alternativePhone: 'Alternative Phone',
      fax: 'Fax',
      email: 'Email',
      website: 'Website',
    },
    noCarriersSelected: 'No carriers selected.',
  },
  validation: {
    contactFirstNameRequired: 'Contact First Name is required',
    contactLastNameRequired: 'Contact Last Name is required',
    contactPhoneRequired: 'Contact Phone Number is required',
    contactPhoneDigits: 'Contact Phone Number must be exactly 10 digits',
    alternativePhoneRequired: 'Alternative Phone Number is required',
    alternativePhoneDigits: 'Alternative Phone Number must be exactly 10 digits',
    faxRequired: 'Fax is required',
    faxDigits: 'Fax must be exactly 10 digits',
    emailRequired: 'Email is required',
    emailInvalid: 'Enter a valid email address',
    nameRequired: 'Parent Company Name is required',
    address1Required: 'Address 1 is required',
    address2Required: 'Address 2 is required',
    cityRequired: 'City is required',
    stateRequired: 'State is required',
    zipRequired: 'Zip Code is required',
    zipDigits: 'Zip Code must be exactly 5 digits',
    duplicateCarriers: 'Duplicate carriers are not allowed',
    fieldRequired: '{{field}} is required',
    fieldTenDigits: '{{field}} must be exactly 10 digits',
  },
  toasts: {
    create: {
      success: 'Parent Company created successfully.',
      error: 'Failed to create parent company. Please try again.',
    },
    update: {
      success: 'Parent Company updated successfully.',
      error: 'Failed to update parent company. Please try again.',
    },
  },
} satisfies ParentCompanyContent
