export const PLAN_CONTENT = {
  list: {
    kicker: 'Plans',
    title: 'Plans',
    description:
      'Manage and view plan data with filters for parent company and carrier.',
    addButton: 'New Plan',
    loadErrorFallback: 'Unable to load plans. Please try again.',
    retry: 'Retry',
  },
  pages: {
    index: {
      kicker: 'Administration',
      title: 'Update Plans',
      description:
        'Select an action below to set up new plans or manage and update existing plans and rates.',
      chooseHeading: 'Select a Task:',
      cards: {
        newPlan: {
          title: 'New Plan Setup',
          description: 'Guided plan setup',
        },
        updatePlan: {
          title: 'Update Current Plans',
          description: 'Update available plans and their rates',
        },
      },
    },
    new: {
      formTitle: 'New Plan',
    },
    edit: {
      kicker: 'Administration',
      title: 'Plan Edit',
      description:
        'Select a plan to load its details, then update using the guided steps.',
      selectLabel: 'Select Plan',
      selectCardDescription:
        'Search by plan name, carrier, or parent company and choose to view or edit.',
      searchPlaceholder: 'Search by plan name...',
      searchButton: 'Search',
      clearButton: 'Clear',
      viewTitle: 'Plan Information',
      viewDescription: 'View complete details for the selected plan record.',
      deleteButton: 'Delete',
      backButton: 'Back',
      editButton: 'Edit',
      confirmDeleteTitle: 'Delete Plan',
      confirmDeletePrompt:
        'Are you sure you want to delete this plan? This action cannot be undone.',
      cancel: 'Cancel',
      confirmDelete: 'Delete Plan',
      loadingDetails: 'Loading plan details...',
      errors: {
        listLoad: 'Failed to load plans. Please try again.',
        detailLoad: 'Failed to load plan details. Please try again.',
      },
    },
  },
  filters: {
    allParentCompanies: 'All Parent Companies',
    allCarriers: 'All Carriers',
    parentCompanyLabel: 'Parent Company',
    carrierLabel: 'Carrier',
    clearFilters: 'Clear Filters',
    loadingMore: 'Loading more...',
    parentCompanyPlaceholder: 'Filter by parent company...',
    carrierPlaceholder: 'Filter by carrier...',
  },
  table: {
    emptyValue: '-',
    columns: {
      name: 'Name',
      coverageCode: 'Coverage Code',
      option: 'Option',
      effectiveDate: 'Effective Date',
      view: 'View',
      edit: 'Edit',
      delete: 'Delete',
    },
    viewAria: (name: string) => `View ${name}`,
    editAria: (name: string) => `Edit ${name}`,
    deleteAria: (name: string) => `Delete ${name}`,
  },
  form: {
    kicker: 'Administration',
    defaultTitle: 'New Plan',
    titles: {
      create: 'Create Plan',
      edit: 'Edit Plan',
    },
    saveLabels: {
      create: 'Save',
      edit: 'Save Changes',
    },
    navigation: {
      back: 'Back',
      next: 'Next',
    },
    steps: [
      { id: 'general', label: 'General', index: 0 },
      { id: 'review', label: 'Review', index: 1 },
    ],
    validationSummary: 'Please fix the highlighted fields before saving.',
    actions: {
      back: 'Back',
      save: 'Save',
    },
  },
  generalStep: {
    heading: 'Plan Information',
    description: 'Enter the main details and configuration for this plan.',
    linkedHeading: 'Linked Plans',
    linkedDescription: 'Optionally link this plan to other existing plans.',
    labels: {
      parentCompany: 'Parent Company',
      coverageCode: 'Coverage Code',
      commissionCode: 'Commission Code',
      option: 'Option',
      name: 'Name',
      effectiveDate: 'Effective Date',
      groupType: 'Group Type',
      linkedPlan: 'Linked Plan',
      linkedPlan2: 'Linked Plan 2',
    },
    placeholders: {
      parentCompanySelect: 'Select parent company...',
      parentCompanyLoading: 'Loading parent companies...',
      coverageCodeSelect: 'Select coverage code...',
      coverageCodeSelectParentCompanyFirst:
        'Select a parent company first...',
      coverageCodeLoading: 'Loading coverage codes...',
      commissionCodeSelect: 'Select commission code...',
      commissionCodeLoading: 'Loading commission codes...',
      option: 'Enter option',
      name: 'Enter plan name',
      effectiveDate: 'Select effective date...',
      groupTypeSelect: 'Select group type...',
      linkedPlanSelect: 'Select a plan (optional)...',
      linkedPlanSelectParentCompanyFirst:
        'Select a parent company first...',
      linkedPlanLoading: 'Loading plans...',
    },
    loadingMore: 'Loading more...',
  },
  reviewStep: {
    heading: 'Review & Save',
    description: 'Confirm all plan details before saving.',
    emptyValue: '—',
    sections: {
      general: 'Plan Information',
      linked: 'Linked Plans',
    },
    fields: {
      parentCompany: 'Parent Company',
      coverageCode: 'Coverage Code',
      commissionCode: 'Commission Code',
      option: 'Option',
      name: 'Plan Name',
      effectiveDate: 'Effective Date',
      groupType: 'Group Type',
      linkedPlan: 'Linked Plan 1',
      linkedPlan2: 'Linked Plan 2',
    },
  },
  validation: {
    parentCompanyRequired: 'Parent Company is required',
    coverageCodeRequired: 'Coverage Code is required',
    commissionCodeRequired: 'Commission Code is required',
    optionRequired: 'Option is required',
    optionMax: 'Option must be 50 characters or fewer',
    nameRequired: 'Name is required',
    nameMax: 'Name must be 100 characters or fewer',
    effectiveDateRequired: 'Effective Date is required',
    groupTypeRequired: 'Group Type is required',
    linkedPlanDuplicateError:
      'Linked Plan and Linked Plan 2 cannot be the same plan',
  },
  toasts: {
    createSuccess: 'Plan created successfully!',
    createError: 'Failed to create plan. Please try again.',
    updateSuccess: 'Plan updated successfully!',
    updateError: 'Failed to update plan. Please try again.',
    deleteSuccess: 'Plan deleted successfully!',
    deleteError: 'Failed to delete plan. Please try again.',
  },
} as const
